version: '3.8'
services:
  frontend:
    container_name: "frontend"
    # ports:
      # - "3003:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_SERVER_URL=${SERVER_URL:-http://localhost}