version: '3.8'
services:
  api:
    build:
      context: ../../
      dockerfile: api/docker/Dockerfile.dev
    working_dir: /app
    entrypoint: /bin/bash
    command: -c "yarn install && yarn dev"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=mysecret
      - API_URL=http://proxy
      - FRONTEND_URL=${SERVER_URL:-http://localhost}
      - ACCESS_JWT_TOKEN_EXPIRATION=15m
      - REFRESH_JWT_TOKEN_EXPIRATION=30d
    volumes:
      - ${PWD}/apps/api:/app
